# -*- coding: utf-8 -*-
"""Initial migration.

Revision ID: 3638847510d4
Revises:
Create Date: 2022-06-09 15:27:40.121566

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3638847510d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():  # noqa: D103
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():  # noqa: D103
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    # ### end Alembic commands ###
